test

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -45,21 +45,21 @@ jobs:
           docker compose build
           docker compose push
 
-      - name: Cleanup Previous Containers
-        run: |
-          docker compose down --remove-orphans || true
+      # - name: Cleanup Previous Containers
+      #   run: |
+      #     docker compose down --remove-orphans || true
 
-      - name: Start Containers
-        run: |
-          docker compose up -d
+      # - name: Start Containers
+      #   run: |
+      #     docker compose up -d
 
-      - name: Archive Logs
-        if: always()
-        run: |
-          docker compose logs --no-color > docker-logs.txt
+      # - name: Archive Logs
+      #   if: always()
+      #   run: |
+      #     docker compose logs --no-color > docker-logs.txt
 
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: docker-logs
-          path: docker-logs.txt
+      # - name: Upload Artifact
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: docker-logs
+      #     path: docker-logs.txt
